version: '3'
services:
    mongodb:
        image: mongo
        container_name: watsana-mongodb
        volumes:
            - ../deployment/watsana/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    web:
        build: .
        image: watsana-image
        container_name: watsana-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9280:9280
        links:
            - mongodb
        networks:
            - default
        restart: always
        environment:
            WATSANA_SETTINGS: /app/watsana-production.cfg
        command:
            /venv/bin/gunicorn -w 2 --bind 0.0.0.0:9280 --env "SCRIPT_NAME=/watsana" --log-file=- --log-level debug --capture-output "watsana.web:create_app()"
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    

networks:
    default:
